name: ML Pipeline

on:
  workflow_dispatch:  
  push:
    branches: [ webadded ] 
env:
  AZURE_WEBAPP_NAME: electricity-forecasting-market

jobs:
  ml-lifecycle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.11'
           
      - name: Install dependencies
        run: |
          pip install -r requirement.txt
          pip install jupyter

      - name: Data Ingestion Fingrid & FMI
        run: |
          python importingDataFinGrid.py
          python importingDataFMI.py

      - name: Data Preprocessing
        run: |
          jupyter nbconvert --to notebook --execute preprocessing.ipynb
          
      - name: Train and Evaluate ML Model
        run: |
          python modelling.py # This assumes modelling.py will execute your training and evaluation logic
          # If your modelling.py requires specific arguments or functions to be called,
          # you might need to adjust this line. For example:
          # python -c "from modelling import train_sarima_model; train_sarima_model()"
          # Or if it has a main function:
          # python -c "from modelling import main; main()"
          
      - name: Prepare Deployment Package
        run: |
          # Buat direktori 'publish' jika belum ada
          mkdir -p ./publish/data/forecasts/
          mkdir -p ./publish/artifacts/metrics/
          mkdir -p ./publish/artifacts/models/ # Untuk model yang sudah dilatih
          mkdir -p ./publish/templates/ # Untuk template HTML
          mkdir -p ./publish/static/
          # Salin semua file aplikasi yang diperlukan ke direktori 'publish'
          # Sesuaikan daftar file/folder ini dengan struktur proyek Anda
          cp app.py ./publish/
          cp requirement.txt ./publish/
          cp -r templates/ ./publish/
          cp -r static/ ./publish/
          # cp trained_model.pkl ./publish/ # Contoh: salin model yang dilatih
          # ... tambahkan file/folder lain yang dibutuhkan App Service Anda

      - name: Upload Application Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-package
          path: ./publish 
    
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [ml-lifecycle]

    steps:
        - uses: actions/checkout@v4

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: webapp-package 
            path: ./downloaded-package

        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: ./downloaded-package
      
      
